### ISSUE TITLE
Possibility of providing .dll plugin?

### ISSUE THREAD

**Issue by banjaminicc** [tongyuantongyu/cycmunet#2]
It would be more convenient for a standalone vapoursynth binary so that this plugin can be used in conjunction with others. Thanks in advance!

**Comment by tongyuantongyu** [comment]
Please checkout https://github.com/tongyuantongyu/vs-NNVISR, which has support for this network, and provides [binary release](https://github.com/tongyuantongyu/vs-NNVISR/releases/tag/v1.0.0-pre5).
